#!/usr/bin/env python3
"""
WAF Detector
--------------
Detects Web Application Firewalls by:
  • Fingerprinting response headers & cookies
  • Sending known WAF-triggering payloads and analyzing 403/406/429 responses
  • Detecting WAF-specific error pages
  • Checking server headers for WAF signatures
"""

import requests
from pathlib import Path
from urllib.parse import urlparse
from typing import Dict, List, Optional, Tuple
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

# ── WAF Signatures ────────────────────────────────────────────────────────────

WAF_SIGNATURES: Dict[str, Dict] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "__cfduid", "cf-request-id"],
        "cookies": ["__cfduid", "__cfuid", "cf_clearance"],
        "body": ["cloudflare", "error 1005", "error 1006", "error 1010", "ray id"],
        "server": ["cloudflare"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": ["aws-waf-token"],
        "body": ["aws", "request blocked"],
        "server": ["awselb", "amazon cloudfront"],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-origin-hop", "x-akamai-transformed"],
        "cookies": ["ak_bmsc", "bm_sz", "bm_sv"],
        "body": ["akamai", "reference #"],
        "server": ["akamai"],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "body": ["incapsula", "imperva"],
        "server": ["incapsula"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security-message"],
        "cookies": [],
        "body": ["mod_security", "modsecurity", "not acceptable", "406 not acceptable"],
        "server": ["mod_security", "modsec"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body": ["sucuri", "access denied - sucuri website firewall"],
        "server": ["sucuri"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["ts", "tsrce", "tsbbl"],
        "body": ["the requested url was rejected", "f5", "big-ip"],
        "server": ["big-ip"],
    },
    "Fortinet FortiWeb": {
        "headers": [],
        "cookies": ["FORTIWAFSID="],
        "body": ["fortinet", "fortigate", "fortiWeb"],
        "server": ["fortiwaf", "fortigate"],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect"],
        "cookies": ["barra_counter_session"],
        "body": ["barracuda", "the page cannot be displayed"],
        "server": ["barracuda"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": [],
        "body": ["wordfence", "generated by wordfence"],
        "server": [],
    },
    "Nginx (generic block)": {
        "headers": [],
        "cookies": [],
        "body": ["nginx", "403 forbidden", "access forbidden"],
        "server": ["nginx"],
    },
    "DenyAll": {
        "headers": ["x-denyall"],
        "cookies": ["sessioncookie"],
        "body": ["denyall"],
        "server": ["denyall"],
    },
    "Wallarm": {
        "headers": ["x-wallarm-node"],
        "cookies": [],
        "body": ["wallarm"],
        "server": ["wallarm"],
    },
}

# Payloads that commonly trigger WAF blocks
WAF_TRIGGER_PAYLOADS = [
    "/?q=<script>alert(1)</script>",
    "/?id=1' OR '1'='1",
    "/?cmd=cat /etc/passwd",
    "/?file=../../../../etc/passwd",
    "/?q=../../../etc/passwd",
    "/?search=<img src=x onerror=alert(1)>",
    "/?id=1 UNION SELECT 1,2,3--",
    "/?input=<?xml version='1.0'?><!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>",
]


# ── WAF Bypass Chain Generator ───────────────────────────────────────────────

BYPASS_CHAINS: Dict[str, List[str]] = {
    "Cloudflare": [
        "URL double-encode: %253Cscript%253E",
        "Unicode fullwidth: ＜script＞alert(1)＜/script＞",
        "Case mixing: <ScRiPt>alert(1)</sCrIpT>",
        "Chunked Transfer-Encoding with TE: chunked header",
        "JSON content-type with GET body bypass",
        "HTTP/2 header smuggling (H2.CL)",
    ],
    "AWS WAF": [
        "SQL: 1/**/UNION/**/SELECT/**/1,2,3--",
        'SQLi via JSON: {"id": "1 OR 1=1"}',
        "XSS: <script\x0a>alert(1)</script>",
        "Tab/newline obfuscation: <scr\tipt>alert(1)</scr\tipt>",
        "HTTP request splitting via CRLF injection",
    ],
    "ModSecurity": [
        "SQL comment bypass: 1 /*!UNION*/ /*!SELECT*/ 1,2--",
        "HPP (HTTP Parameter Pollution): ?id=1&id=UNION&id=SELECT",
        "Multipart boundary bypass for file uploads",
        "XSS: <img/src='x'onerror=alert(1)>",
        "URL path bypass: /admin%2F → /admin/",
    ],
    "Imperva / Incapsula": [
        "SQLi via hex encoding: 0x53454c454354",
        "XSS: <details/open/ontoggle=alert(1)>",
        "User-Agent spoofing: Googlebot/2.1",
        "Rate limit bypass via X-Forwarded-For rotation",
    ],
    "Akamai": [
        "Slow HTTP POST (low-and-slow evasion)",
        "Gzip/deflate payload encoding",
        "SQLi via CHAR(): CHAR(83)+CHAR(69)+CHAR(76)...",
        'XSS in JSON context: "onmouseover":"alert(1)"',
    ],
    "F5 BIG-IP ASM": [
        "HTTP verb tampering: use TRACE/PATCH instead of GET",
        "XML body injection with CDATA bypass",
        "XSS via SVG: <svg><animate onbegin=alert(1)>",
        "SQLi via time delay with benchmark()",
    ],
    "default": [
        "Encode payloads: URL / double-URL / HTML entity / Unicode",
        "Case variation: SeLeCt, UnIoN",
        "Comment insertion: UN/**/ION SE/**/LECT",
        "HTTP Parameter Pollution",
        "Null byte injection: %00",
        "Content-Type switching: JSON/XML/multipart",
        "Slow HTTP techniques",
        "IPv6 address in Host header",
    ],
}


class BypassChainGenerator:
    """Generate WAF-specific bypass payloads based on detected WAF."""

    @staticmethod
    def generate(
        waf_name: str, base_payload: str = "<script>alert(1)</script>"
    ) -> List[Dict]:
        """Return a list of bypass technique findings for the detected WAF."""
        chains = BYPASS_CHAINS.get(waf_name, BYPASS_CHAINS["default"])
        results = []

        # Encode the base_payload in all standard ways
        encoded_variants = BypassChainGenerator._encode_variants(base_payload)

        for technique in chains:
            results.append(
                {
                    "type": f"WAF Bypass Technique — {waf_name}",
                    "waf_name": waf_name,
                    "severity": "info",
                    "technique": technique,
                    "detail": f"Bypass technique for {waf_name}: {technique}",
                    "evidence": f"Recommended bypass against {waf_name} WAF",
                    "owasp": "Informational",
                    "cvss": 0.0,
                    "remediation": "Update WAF rules and test against bypass vectors regularly.",
                }
            )

        # Add encoded payload variants
        for label, encoded in encoded_variants.items():
            results.append(
                {
                    "type": f"WAF Bypass Payload — {label}",
                    "waf_name": waf_name,
                    "severity": "info",
                    "technique": label,
                    "detail": f"Encoded variant: {encoded[:120]}",
                    "evidence": f"Payload: {encoded[:120]}",
                    "owasp": "Informational",
                    "cvss": 0.0,
                    "remediation": "Ensure WAF rules handle all encoding variants.",
                }
            )

        return results

    @staticmethod
    def _encode_variants(payload: str) -> Dict[str, str]:
        """Produce common encoding variants of a payload."""
        from urllib.parse import quote
        import html

        variants = {
            "URL-encoded": quote(payload),
            "Double URL-encoded": quote(quote(payload)),
            "HTML-entity": html.escape(payload),
            "Unicode escape": payload.encode("unicode_escape").decode(),
            "Hex (JS)": "".join(f"\\x{ord(c):02x}" for c in payload),
            "Base64": __import__("base64").b64encode(payload.encode()).decode(),
            "Null-byte": payload.replace("<", "\x00<"),
            "Tab-obfuscated": payload.replace("script", "scr\tipt"),
            "Case-mixed": "".join(
                c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(payload)
            ),
        }
        return variants


class WAFDetector:
    """Web Application Firewall detection and fingerprinting."""

    def __init__(self, target: str, timeout: int = 10, session=None):
        self.target = target.rstrip("/")
        self.timeout = timeout
        if session is not None:
            self.session = session
        else:
            self.session = requests.Session()
            self.session.headers["User-Agent"] = (
                "Mozilla/5.0 (compatible; SecurityScanner/1.0)"
            )
        self.results: List[Dict] = []

    # ── Fingerprint from clean response ────────────────────────────────

    def _fingerprint_clean(self) -> List[str]:
        """Check WAF signatures on a clean (non-attack) request."""
        detected = []
        try:
            resp = self.session.get(
                self.target,
                timeout=self.timeout,
                verify=False,
                allow_redirects=True,
            )
            self._check_response(resp, detected, attack_mode=False)
        except Exception:
            pass
        return detected

    def _check_response(
        self, resp: requests.Response, detected: List[str], attack_mode: bool = True
    ) -> None:
        """Fingerprint a response against all WAF signatures."""
        headers_lower = {k.lower(): v.lower() for k, v in resp.headers.items()}
        cookies_str = " ".join(resp.cookies.keys()).lower()
        body_lower = resp.text[:5000].lower()
        server_lower = headers_lower.get("server", "")

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0
            matched = []

            for h in sigs["headers"]:
                if h.lower() in headers_lower:
                    score += 2
                    matched.append(f"header:{h}")

            for c in sigs["cookies"]:
                if c.lower() in cookies_str:
                    score += 2
                    matched.append(f"cookie:{c}")

            for b in sigs["body"]:
                if b.lower() in body_lower:
                    score += 1
                    matched.append(f"body:{b}")

            for s in sigs["server"]:
                if s.lower() in server_lower:
                    score += 3
                    matched.append(f"server:{s}")

            threshold = 2 if attack_mode else 3
            if score >= threshold and waf_name not in detected:
                detected.append(waf_name)

    # ── Test with attack payloads ───────────────────────────────────────

    def _fingerprint_attack(self) -> Tuple[List[str], List[int]]:
        """Send attack payloads, collect detected WAFs and status codes."""
        detected = []
        statuses = []
        parsed = urlparse(self.target)
        base = f"{parsed.scheme}://{parsed.netloc}"

        for path in WAF_TRIGGER_PAYLOADS:
            try:
                resp = self.session.get(
                    base + path,
                    timeout=self.timeout,
                    verify=False,
                    allow_redirects=False,
                )
                statuses.append(resp.status_code)
                if resp.status_code in (400, 403, 406, 429, 503):
                    self._check_response(resp, detected, attack_mode=True)
            except Exception:
                pass

        return detected, statuses

    # ── Public run ─────────────────────────────────────────────────────

    def run(self) -> List[Dict]:
        console.print("  [dim]-> Probing for WAF signatures...[/dim]")

        with Progress(
            SpinnerColumn(),
            TextColumn("[cyan]WAF detection...[/cyan]"),
            console=console,
        ) as progress:
            progress.add_task("waf", total=None)
            clean_waf = self._fingerprint_clean()
            attack_waf, statuses = self._fingerprint_attack()

        all_detected = list(dict.fromkeys(clean_waf + attack_waf))
        blocked_count = sum(1 for s in statuses if s in (400, 403, 406, 429, 503))

        if all_detected:
            for waf in all_detected:
                finding = {
                    "type": "WAF Detected",
                    "waf_name": waf,
                    "severity": "info",
                    "detail": (
                        f"Web Application Firewall identified: {waf}. "
                        f"{blocked_count}/{len(WAF_TRIGGER_PAYLOADS)} attack payloads blocked."
                    ),
                    "evidence": f"WAF: {waf} | Blocked: {blocked_count}/{len(WAF_TRIGGER_PAYLOADS)}",
                    "owasp": "Informational",
                    "cvss": 0.0,
                    "remediation": f"WAF '{waf}' detected — bypass techniques generated below.",
                }
                self.results.append(finding)
                console.print(f"  [yellow]⚠  WAF Detected: [bold]{waf}[/bold][/yellow]")
                console.print(
                    f"     Blocked {blocked_count}/{len(WAF_TRIGGER_PAYLOADS)} attack payloads"
                )
                # Auto-generate bypass chains
                bypasses = BypassChainGenerator.generate(waf)
                self.results.extend(bypasses)
                console.print(
                    f"  [cyan]  → {len(bypasses)} bypass technique(s) generated for {waf}[/cyan]"
                )
        else:
            if blocked_count > len(WAF_TRIGGER_PAYLOADS) // 2:
                finding = {
                    "type": "WAF Detected (Unknown)",
                    "waf_name": "Unknown WAF / Custom Filter",
                    "severity": "info",
                    "detail": (
                        f"Possible unidentified WAF: {blocked_count}/{len(WAF_TRIGGER_PAYLOADS)} "
                        "attack payloads blocked but no known WAF signature matched."
                    ),
                    "evidence": f"Blocked: {blocked_count}/{len(WAF_TRIGGER_PAYLOADS)}",
                    "owasp": "Informational",
                    "cvss": 0.0,
                    "remediation": "Investigate blocking rules. Test with manual bypass payloads.",
                }
                self.results.append(finding)
                self.results.extend(BypassChainGenerator.generate("default"))
                console.print(
                    "  [yellow]⚠  Unknown WAF/Filter — generic bypass chains added[/yellow]"
                )
            else:
                console.print("  [green]✅ No WAF detected[/green]")

        return self.results
